### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by l3r8yJ** [l3r8yJ/rjini#1]
@rultor hello

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#3](https://github.com/l3r8yJ/rjini/issues/3) is still not solved.

**Comment by l3r8yJ** [comment]
@rultor release, tag is `0.0.1`

**Comment by l3r8yJ** [comment]
@rultor release, tag is `0.0.1`

**Comment by 0pdd** [comment]
@l3r8yJ the only puzzle [#3](https://github.com/l3r8yJ/rjini/issues/3) is solved here.

**Comment by l3r8yJ** [comment]
@rultor release, tag is `0.1.0`

**Comment by l3r8yJ** [comment]
@rultor release, tag is `0.0.1`

**Comment by l3r8yJ** [comment]
@rultor release, tag is `0.0.1`

**Comment by l3r8yJ** [comment]
@rultor release, tag is `0.0.1`

**Comment by l3r8yJ** [comment]
@rultor release, tag is `0.0.1`

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#12](https://github.com/l3r8yJ/rjini/issues/12) is still not solved; solved: [#3](https://github.com/l3r8yJ/rjini/issues/3), [#9](https://github.com/l3r8yJ/rjini/issues/9).
