### ISSUE TITLE
lib.rs:1-2: Need to create struct Jini. It has to...

### ISSUE THREAD

**Issue by 0pdd** [l3r8yJ/rjini#3]
The puzzle `1-d228d94f` from #1 has to be resolved: 

https://github.com/l3r8yJ/rjini/blob/ac756f79102026b049f73452a31adea6333562f8/src/lib.rs#L1-L2

The puzzle was created by @rultor on 20-Feb-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by l3r8yJ** [comment]
start development after closing [this](https://github.com/l3r8yJ/jini/issues/10)
